server:
  port: 8020
spring:
  application:
    name: consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
springdoc:
  api-docs:
    enabled: true
    path: /swagger-ui/api-docs
  swagger-ui:
    path: /swagger-ui/index.html
  packages-to-scan: com.cuit.consumer